# Generated by Django 3.2.9 on 2021-11-24 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_language', models.CharField(max_length=200)),
                ('language_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_summary', models.CharField(max_length=200)),
                ('language_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='personalProject.projectlanguage', verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 38, 13, 13093), verbose_name='date published')),
                ('project_slug', models.CharField(default=1, max_length=200)),
                ('project_overview', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='personalProject.projectoverview', verbose_name='Series')),
            ],
        ),
    ]
